# Generated by Django 4.0.10 on 2023-05-04 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general_information', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='День народження')),
                ('phone_number', models.CharField(blank=True, max_length=15, verbose_name='Номер телефона')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Домашня адреса')),
                ('teacher_id', models.CharField(max_length=15, unique=True, verbose_name='Унікальний номер у системі')),
                ('hire_date', models.DateField(verbose_name='Дата прийняття на роботу')),
                ('department', models.ManyToManyField(help_text='Структурний підрозділ (кафедра або інший підрозділ), відповідальний за реалізацію ОП', to='general_information.structuralsubdivision', verbose_name='Структурний підрозділ')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Викладач',
                'verbose_name_plural': 'Викладачі',
                'db_table': 'Teacher',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='День народження')),
                ('phone_number', models.CharField(blank=True, max_length=15, verbose_name='Номер телефона')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Домашня адреса')),
                ('student_id', models.CharField(max_length=15, unique=True, verbose_name='Унікальний номер у системі')),
                ('enrollment_date', models.DateField(verbose_name='Дата вступу в заклад освіти')),
                ('student_type', models.IntegerField(choices=[('1', 'Бакалавр'), ('2', 'Магістр'), ('3', 'Аспірант')], verbose_name='Освітній ступінь')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенти',
                'db_table': 'student',
            },
        ),
    ]
