# Generated by Django 4.0.10 on 2024-10-10 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_teacher_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="experience_years",
            field=models.IntegerField(default=0, verbose_name="Стаж роботи"),
        ),
        migrations.AddField(
            model_name="teacher",
            name="position",
            field=models.CharField(blank=True, max_length=255, verbose_name="Посада"),
        ),
        migrations.AddField(
            model_name="teacher",
            name="subjects",
            field=models.TextField(blank=True, verbose_name="Навчальні дисципліни"),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="hire_date",
            field=models.DateField(blank=True, verbose_name="Дата прийняття на роботу"),
        ),
        migrations.CreateModel(
            name="TeacherFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="uploads/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.teacher"
                    ),
                ),
            ],
        ),
    ]
