# Generated by Django 4.0.10 on 2024-10-10 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_teacher_experience_years_teacher_position_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="is_approved",
            field=models.BooleanField(
                default=False, verbose_name="Підтверджений викладач"
            ),
        ),
    ]
