# Generated by Django 4.0.10 on 2024-10-10 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_teacher_is_approved"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="hire_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата прийняття на роботу"
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="subjects",
            field=models.TextField(
                blank=True, null=True, verbose_name="Навчальні дисципліни"
            ),
        ),
    ]
