# Generated by Django 4.0.10 on 2024-10-10 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_teacher_hire_date_alter_teacher_subjects"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="student_id",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                unique=True,
                verbose_name="Унікальний номер у системі",
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="teacher_id",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                unique=True,
                verbose_name="Унікальний номер у системі",
            ),
        ),
    ]
