# Generated by Django 4.0.10 on 2024-10-12 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_user_first_name_user_last_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacher",
            name="subjects",
        ),
        migrations.AddField(
            model_name="teacher",
            name="qualification",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Кваліфікація викладача"
            ),
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Навчальна дисципліна"
                    ),
                ),
                (
                    "citation_data",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Citation Data"
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subjects",
                        to="users.teacher",
                    ),
                ),
            ],
            options={
                "verbose_name": "Навчальна дисципліна",
                "verbose_name_plural": "Навчальні дисципліни",
                "db_table": "Subject",
            },
        ),
    ]
