# Generated by Django 4.0.10 on 2024-10-15 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_remove_teacher_subjects_teacher_qualification_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Назва курсу")),
            ],
        ),
        migrations.CreateModel(
            name="ProfessionalActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "paragraph",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Параграф"
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст")),
            ],
        ),
        migrations.CreateModel(
            name="ProfessionalDevelopment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        max_length=255, verbose_name="Тип (сертифікат, свідоцтво)"
                    ),
                ),
                ("details", models.TextField(verbose_name="Деталі")),
                ("date", models.DateField(blank=True, null=True, verbose_name="Дата")),
                (
                    "duration",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Тривалість"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Qualification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "qualification_name",
                    models.CharField(max_length=255, verbose_name="Назва кваліфікації"),
                ),
                ("details", models.TextField(blank=True, verbose_name="Деталі")),
                (
                    "date_awarded",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата присудження"
                    ),
                ),
                (
                    "dissertation_topic",
                    models.TextField(blank=True, verbose_name="Тема дисертації"),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="teacher",
            name="teacher_id",
        ),
        migrations.AddField(
            model_name="user",
            name="middle_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="По батькові"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(blank=True, max_length=100, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(blank=True, max_length=100, verbose_name="Прізвище"),
        ),
        migrations.DeleteModel(
            name="Subject",
        ),
        migrations.AddField(
            model_name="qualification",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="qualifications",
                to="users.teacher",
            ),
        ),
        migrations.AddField(
            model_name="professionaldevelopment",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="professional_development",
                to="users.teacher",
            ),
        ),
        migrations.AddField(
            model_name="professionalactivity",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="professional_activities",
                to="users.teacher",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="users.teacher",
            ),
        ),
    ]
