# Generated by Django 4.0.10 on 2024-10-15 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_course_professionalactivity_professionaldevelopment_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Навчальна дисципліна"
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subjects",
                        to="users.teacher",
                    ),
                ),
            ],
            options={
                "verbose_name": "Навчальна дисципліна",
                "verbose_name_plural": "Навчальні дисципліни",
                "db_table": "Subject",
            },
        ),
    ]
