# Generated by Django 4.0.10 on 2024-10-15 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("general_information", "0005_alter_educationstatistics_study_course_year"),
        ("users", "0010_subject"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="teacher",
            options={},
        ),
        migrations.RemoveField(
            model_name="teacher",
            name="address",
        ),
        migrations.RemoveField(
            model_name="teacher",
            name="birthdate",
        ),
        migrations.RemoveField(
            model_name="teacher",
            name="phone_number",
        ),
        migrations.AddField(
            model_name="teacher",
            name="first_name",
            field=models.CharField(default="", max_length=100, verbose_name="Ім'я"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="teacher",
            name="last_name",
            field=models.CharField(default="", max_length=100, verbose_name="Прізвище"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="teacher",
            name="middle_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="По батькові"
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="department",
            field=models.ManyToManyField(
                to="general_information.structuralsubdivision",
                verbose_name="Структурний підрозділ",
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="teacher",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterModelTable(
            name="teacher",
            table=None,
        ),
    ]
