# Generated by Django 4.0.10 on 2024-10-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_alter_education_graduation_year_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="education",
            name="graduation_year",
        ),
        migrations.RemoveField(
            model_name="education",
            name="institution",
        ),
        migrations.RemoveField(
            model_name="education",
            name="qualification_awarded",
        ),
        migrations.RemoveField(
            model_name="education",
            name="specialty",
        ),
        migrations.AddField(
            model_name="education",
            name="text",
            field=models.CharField(default="", max_length=600, verbose_name="Освіта"),
            preserve_default=False,
        ),
    ]
