# Generated by Django 4.0.10 on 2024-10-15 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_remove_education_graduation_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='date_awarded',
            field=models.DateField(blank=True, null=True, verbose_name='Дата присудження або код спеціальності'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='experience_years',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Стаж роботи'),
        ),
    ]
