# Generated by Django 4.0.10 on 2024-10-15 17:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_qualification_date_awarded_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='experience_years',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None, verbose_name='Стаж роботи'),
        ),
    ]
