# Generated by Django 4.0.10 on 2024-10-16 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_teacher_experience_years'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qualification',
            old_name='qualification_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='date_awarded',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='details',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='dissertation_topic',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='qualification',
        ),
        migrations.AddField(
            model_name='qualification',
            name='code',
            field=models.CharField(default='', max_length=100, verbose_name='Код кваліфікації'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qualification',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата присудження'),
        ),
        migrations.AddField(
            model_name='qualification',
            name='text',
            field=models.TextField(blank=True, verbose_name='Текст кваліфікації'),
        ),
        migrations.CreateModel(
            name='AcademicDegree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=600, verbose_name='Назва наукового ступеня')),
                ('details', models.TextField(blank=True, null=True, verbose_name='Деталі')),
                ('date_awarded', models.DateField(blank=True, null=True, verbose_name='Дата присудження або код спеціальності')),
                ('dissertation_topic', models.TextField(blank=True, null=True, verbose_name='Тема дисертації')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_degrees', to='users.teacher')),
            ],
        ),
    ]
