# Generated by Django 4.0.10 on 2024-10-16 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0019_rename_qualification_name_qualification_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Прізвище')),
                ('first_name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='По-батькові')),
            ],
        ),
        migrations.AddField(
            model_name='professionalactivity',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='professionalactivity',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Назва публікації або діяльності', max_length=500, verbose_name='Назва професійної діяльності')),
                ('publication_year', models.CharField(help_text='Рік, коли було опубліковано або здійснено діяльність', max_length=4, verbose_name='Рік публікації')),
                ('publisher_name', models.CharField(blank=True, help_text='Назва організації або видавництва, якщо застосовується', max_length=255, verbose_name='Назва видавництва або організації')),
                ('publication_city', models.CharField(blank=True, help_text='Місто, де відбулася діяльність або публікація', max_length=100, verbose_name='Місто публікації')),
                ('pages', models.CharField(blank=True, help_text='Сторінки, якщо це друкований документ', max_length=50, verbose_name='Сторінки')),
                ('document_type', models.CharField(choices=[('book', 'Книга'), ('article', 'Стаття'), ('conference', 'Матеріали конференції'), ('patent', 'Патент'), ('other', 'Інше')], help_text='Тип джерела для цитування', max_length=100, verbose_name='Тип документа')),
                ('authors', models.ManyToManyField(related_name='citations', to='users.author', verbose_name='Автори')),
            ],
        ),
    ]
