# Generated by Django 4.0.10 on 2024-10-16 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_author_professionalactivity_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='short_name',
            field=models.CharField(blank=True, max_length=255, verbose_name="Скорочене ім'я"),
        ),
    ]
