# Generated by Django 4.0.10 on 2023-05-04 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ControlMeasuresAndAcademicIntegrity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Опишіть, яким чином форми контрольних заходів у межах навчальних дисциплін                    ОП дозволяють перевірити досягнення програмних результатів навчання?",
                        max_length=3000,
                        verbose_name="Опис форм контрольних заходів",
                    ),
                ),
                (
                    "clarity_criteria",
                    models.TextField(
                        help_text="Яким чином забезпечуються чіткість та зрозумілість форм контрольних заходів                    та критеріїв оцінювання навчальних досягнень здобувачів вищої освіти?",
                        max_length=1500,
                        verbose_name="Чіткість та зрозумілість форм",
                    ),
                ),
                (
                    "information_provision",
                    models.TextField(
                        help_text="Яким чином і у які строки інформація про форми контрольних заходів                    та критерії оцінювання доводяться до здобувачів вищої освіти?",
                        max_length=1500,
                        verbose_name="Надання інформації здобувачам",
                    ),
                ),
                (
                    "compliance_requirements",
                    models.TextField(
                        help_text="Яким чином форми атестації здобувачів вищої освіти відповідають                    вимогам стандарту вищої освіти (за наявності)?",
                        max_length=1500,
                        verbose_name="Відповідність форм атестації",
                    ),
                ),
                (
                    "accessibility_certification_procedure",
                    models.TextField(
                        help_text="Яким документом ЗВО регулюється процедура проведення контрольних заходів? Яким чином забезпечується його доступність для учасників освітнього процесу?",
                        max_length=1500,
                        verbose_name="Процедура проведення контрольних заходів",
                    ),
                ),
                (
                    "objectivity_procedures",
                    models.TextField(
                        help_text="Яким чином ці процедури забезпечують об’єктивність екзаменаторів? Якими є процедури запобігання та врегулювання конфлікту інтересів? Наведіть приклади застосування відповідних процедур на ОП",
                        max_length=1500,
                        verbose_name="Процедури врегулювання конфлікту інтересів. Процедури об'єктивності єкзаменаторів",
                    ),
                ),
                (
                    "repeating_control_measures_procedures",
                    models.TextField(
                        help_text="Яким чином процедури ЗВО урегульовують порядок повторного проходження контрольних заходів? Наведіть приклади застосування відповідних правил на ОП",
                        max_length=1500,
                        verbose_name="Процедури врегулювання порядку повторного проходження контрольних заходів",
                    ),
                ),
                (
                    "appeal_procedure_and_results_of_control_measures",
                    models.TextField(
                        help_text="Яким чином процедури ЗВО урегульовують порядок оскарження процедури та результатів проведення контрольних заходів? Наведіть приклади застосування відповідних правил на ОП",
                        max_length=1500,
                        verbose_name="Процедури врегулювання порядку повторного проходження контрольних заходів",
                    ),
                ),
                (
                    "policies_and_standards_documents",
                    models.TextField(
                        help_text="Які документи ЗВО містять політику, стандарт и і процедури дотримання академічної доброчесності?",
                        max_length=1500,
                        verbose_name="Документи про політику, стандарти, процедури академічної доброчесності",
                    ),
                ),
                (
                    "combating_violations_of_academic_integrity_solutions",
                    models.TextField(
                        help_text="Які технологічні рішення використовуються на ОП як інструменти протидії порушенням академічної доброчесності?",
                        max_length=1500,
                        verbose_name="Технологічні рішення протидії порушенням академічної доброчесності",
                    ),
                ),
                (
                    "promoting_academic_integrity",
                    models.TextField(
                        help_text="Яким чином ЗВО популяризує академічну доброчесність серед здобувачів вищої освіти ОП?",
                        max_length=1500,
                        verbose_name="Популярізація академічної доброчесності",
                    ),
                ),
                (
                    "responding_to_violations_of_academic_integrity",
                    models.TextField(
                        help_text="Яким чином ЗВО реагує на порушення академічної доброчесності? Наведіть приклади відповідних ситуацій щодо здобувачів вищої освіти відповідної ОП",
                        max_length=1500,
                        verbose_name="Реагування на порушення академічної доброчесності",
                    ),
                ),
            ],
            options={
                "verbose_name": "Контрольний захід, оцінювання здобувача вищої освіти та академічна доброчесність",
                "verbose_name_plural": "Контрольні заходи, оцінювання здобувачів вищої освіти та академічна доброчесність",
                "db_table": "control_measures_and_academic_integrity",
            },
        ),
        migrations.CreateModel(
            name="EducationalEnvironmentAndMaterialResources",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "financial_resources",
                    models.TextField(
                        help_text="Продемонструйте, яким чином фінансові та матеріально-технічні ресурси (бібліотека, інша інфраструктура, обладнання тощо), а також навчально-методичне забезпечення ОП забезпечують досягнення визначених ОП цілей та програмних результатів навчання?",
                        max_length=1500,
                        verbose_name="Фінансові та матеріально-технічні ресурси",
                    ),
                ),
                (
                    "educational_environment",
                    models.TextField(
                        help_text="Продемонструйте, яким чином освітнє середовище, створене у ЗВО, дозволяє задовольнити потреби та інтереси здобувачів вищої освіти ОП? Які заходи вживаються ЗВО задля виявлення і врахування цих потреб та інтересів?",
                        max_length=1500,
                        verbose_name="Освітнє середовище",
                    ),
                ),
                (
                    "safety_measures",
                    models.TextField(
                        help_text="Опишіть, яким чином ЗВО забезпечує безпечність освітнього середовища для життя та здоров’я здобувачів вищої освіти (включаючи психічне здоров’я)",
                        max_length=1500,
                        verbose_name="Безпека освітнього середовища",
                    ),
                ),
                (
                    "support_services",
                    models.TextField(
                        help_text="Опишіть механізми освітньої, організаційної, інформаційної, консультативної та соціальної підтримки здобувачів вищої освіти? Яким є рівень задоволеності здобувачів вищої освіти цією підтримкою відповідно до результатів опитувань?",
                        max_length=3000,
                        verbose_name="Підтримка здобувачів вищої освіти",
                    ),
                ),
                (
                    "special_needs_people_education",
                    models.TextField(
                        help_text="Яким чином ЗВО створює достатні умови для реалізації права на освіту особами з особливими освітніми потребами? Наведіть конкретні приклади створення таких умов на ОП (якщо такі були)",
                        max_length=1500,
                        verbose_name="Освіта осіб з особливими потребами",
                    ),
                ),
                (
                    "policy_and_procedures_for_conflict_resolution",
                    models.TextField(
                        help_text="Яким чином у ЗВО визначено політику та процедури врегулювання конфліктних ситуацій (включаючи пов’язаних із сексуальними домаганнями, дискримінацією та корупцією)? Яким чином забезпечується їх доступність політики та процедур врегулювання для учасників освітнього процесу? Якою є практика їх застосування під час реалізації ОП?",
                        max_length=3000,
                        verbose_name="Політика та процедури врегулювання конфліктних ситуацій",
                    ),
                ),
            ],
            options={
                "verbose_name": "Освітнє середовище та матеріальний ресурс",
                "verbose_name_plural": "Освітні середовища та матеріальні ресурси",
                "db_table": "educational_environment_and_material_resources",
            },
        ),
        migrations.CreateModel(
            name="EducationalProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Продемонструйте, що зміст освітньо-наукової програми відповідає науковим інтересам аспірантів (ад’юнктів)",
                        max_length=1500,
                        verbose_name="Відповідність ОП науковим інтересам аспірантів",
                    ),
                ),
                (
                    "research_preparation",
                    models.TextField(
                        help_text="Опишіть, яким чином зміст освітньо-наукової програми забезпечує повноцінну підготовку здобувачів вищої освіти до дослідницької діяльності за спеціальністю та/або галуззю",
                        max_length=3000,
                        verbose_name="Підготовка до дослідницької діяльності",
                    ),
                ),
                (
                    "teaching_preparation",
                    models.TextField(
                        help_text="Опишіть, яким чином зміст освітньо-наукової програми забезпечує повноцінну підготовку здобувачів вищої освіти до викладацької діяльності у закладах вищої освіти за спеціальністю та/або галуззю",
                        max_length=3000,
                        verbose_name="Підготовка до викладацької діяльності у ЗВО",
                    ),
                ),
                (
                    "supervisor_relevance",
                    models.TextField(
                        help_text="Продемонструйте дотичність тем наукових досліджень аспірантів (ад’юнктів) напрямам досліджень наукових керівників",
                        max_length=1500,
                        verbose_name="Дотичність тем наукових досліджень аспірантів та керівників",
                    ),
                ),
                (
                    "research_support",
                    models.TextField(
                        help_text="Опишіть з посиланням на конкретні приклади, як ЗВО організаційно та матеріально забезпечує в межах освітньо-наукової програми можливості для проведення і апробації результатів наукових досліджень аспірантів (ад’юнктів)",
                        max_length=1500,
                        verbose_name="Можливості для проведення і апробації наукових досліджень",
                    ),
                ),
                (
                    "international_participation",
                    models.TextField(
                        help_text="Проаналізуйте, як ЗВО забезпечує можливості для долучення аспірантів (ад’юнктів) до міжнародної академічної спільноти за спеціальністю, наведіть конкретні проекти та заходи",
                        max_length=1500,
                        verbose_name="Долучення аспірантів до міжнародної академічної спільноти",
                    ),
                ),
                (
                    "research_projects_supervisors_participation",
                    models.TextField(
                        help_text="Опишіть участь наукових керівників аспірантів у дослідницьких проектах, результати яких регулярно публікуються та/або практично впроваджуються",
                        max_length=1500,
                        verbose_name="Участь наукових керівників у дослідницьких проектах",
                    ),
                ),
                (
                    "academic_integrity_practices",
                    models.TextField(
                        help_text="Опишіть чинні практики дотримання академічної доброчесності у науковій діяльності наукових керівників та аспірантів (ад’юнктів)",
                        max_length=1500,
                        verbose_name="Практики дотримання академічної доброчесності",
                    ),
                ),
                (
                    "academic_integrity_preventing_violations",
                    models.TextField(
                        help_text="Продемонструйте, що ЗВО вживає заходів для виключення можливості здійснення наукового керівництва особами, які вчинили порушення академічної доброчесності",
                        max_length=1500,
                        verbose_name="Запобігання порушенню академічної доброчесності",
                    ),
                ),
            ],
            options={
                "verbose_name": "Прозорість та публічність",
                "verbose_name_plural": "Прозорість та публічність",
                "db_table": "educational_program",
            },
        ),
        migrations.CreateModel(
            name="EducationalProgramAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "admission_rules_link",
                    models.URLField(
                        help_text="Наведіть посилання на веб-сторінку, яка містить інформацію про правила прийому на навчання та вимоги до вступників ОП",
                        verbose_name="Посилання на правила прийому",
                    ),
                ),
                (
                    "admission_requirements",
                    models.TextField(
                        help_text="Поясніть, як правила прийому на навчання та вимоги до вступників ураховують особливості ОП?",
                        max_length=1500,
                        verbose_name="Вимоги до вступників та їх урахування особливостей ОП",
                    ),
                ),
                (
                    "recognition_of_education_results_accessibility",
                    models.TextField(
                        help_text="Яким документом ЗВО регулюється питання визнання результатів навчання, отриманих в інших ЗВО? Яким чином забезпечується його доступність для учасників освітнього процесу?",
                        max_length=1500,
                        verbose_name="Доступність документа про визнання результатів навчання",
                    ),
                ),
                (
                    "admission_requirements_applying_rules_practice",
                    models.TextField(
                        help_text="Опишіть на конкретних прикладах практику застосування вказаних правил на відповідній ОП (якщо такі були)?",
                        max_length=1500,
                        verbose_name="Практика застосування вказаних правил",
                    ),
                ),
                (
                    "recognition_of_education_results_doc",
                    models.TextField(
                        help_text="Яким документом ЗВО регулюється питання визнання результатів навчання, отриманих у неформальній освіті? Яким чином забезпечується його доступність для учасників освітнього процесу?",
                        max_length=1500,
                        verbose_name="Документ, що регулює визнання результатів навчання",
                    ),
                ),
                (
                    "education_results_doc_applying_rules_practice",
                    models.TextField(
                        help_text="Опишіть на конкретних прикладах практику застосування вказаних правил на відповідній ОП (якщо такі були)?",
                        max_length=1500,
                        verbose_name="Практика застосування вказаних правил",
                    ),
                ),
            ],
            options={
                "verbose_name": "Доступ до освітньої програми, результатів навчання",
                "verbose_name_plural": "Доступ до освітніх програм, результатів навчання",
                "db_table": "educational_program_access",
            },
        ),
        migrations.CreateModel(
            name="EducationalProgramDesign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "goals",
                    models.TextField(
                        help_text="Якими є цілі ОП? У чому полягають особливості (унікальність) цієї програми? ",
                        max_length=1500,
                        verbose_name="Цілі ОП",
                    ),
                ),
                (
                    "uniqueness",
                    models.TextField(
                        help_text="Продемонструйте, із посиланням на конкретні документи ЗВО, що цілі ОП відповідають місії та стратегії ЗВО",
                        max_length=3000,
                        verbose_name="Відповідність ОП до місії та стратегії ЗВО",
                    ),
                ),
                (
                    "stakeholder_student",
                    models.TextField(
                        help_text="Опишіть, яким чином інтереси та пропозиції таких груп заінтересованих сторін (стейкхолдерів) були враховані під час формулювання цілей та програмних результатів навчання ОП для здобувачів вищої освіти та випускників програми",
                        max_length=1500,
                        verbose_name="Врахування інтересів стейкхолдерів для здобувачів",
                    ),
                ),
                (
                    "stakeholder_employer",
                    models.TextField(
                        help_text="Опишіть, яким чином інтереси та пропозиції таких груп заінтересованих сторін (стейкхолдерів) були враховані під час формулювання цілей та програмних результатів навчання ОП для роботодавців",
                        max_length=1500,
                        verbose_name="Врахування інтересів стейкхолдерів для роботодавців",
                    ),
                ),
                (
                    "stakeholder_academic",
                    models.TextField(
                        help_text="Опишіть, яким чином інтереси та пропозиції таких груп заінтересованих сторін (стейкхолдерів) були враховані під час формулювання цілей та програмних результатів навчання ОП для академічної спільноти",
                        max_length=1500,
                        verbose_name="Врахування інтересів стейкхолдерів для академічної спільноти",
                    ),
                ),
                (
                    "stakeholder_other",
                    models.TextField(
                        help_text="Опишіть, яким чином інтереси та пропозиції таких груп заінтересованих сторін (стейкхолдерів) були враховані під час формулювання цілей та програмних результатів навчання ОП для інших стейкхолдерів",
                        max_length=1500,
                        verbose_name="Врахування інтересів стейкхолдерів для інших стейкхолдерів",
                    ),
                ),
                (
                    "market_trends",
                    models.TextField(
                        help_text="Продемонструйте, яким чином цілі та програмні результати навчання ОП відбивають тенденції розвитку спеціальності та ринку праці",
                        max_length=1500,
                        verbose_name="Тенденції розвитку спеціальності та ринку праці",
                    ),
                ),
                (
                    "industry_and_regional_context",
                    models.TextField(
                        help_text="Продемонструйте, яким чином під час формулювання цілей та програмних результатів навчання ОП було враховано галузевий та регіональний контекст",
                        max_length=1500,
                        verbose_name="Врахування галузевого та регіонального контексту",
                    ),
                ),
                (
                    "domestic_and_foreign_programs_experience",
                    models.TextField(
                        help_text="Продемонструйте, яким чином під час формулювання цілей та програмних результатів навчання ОП було враховано досвід аналогічних вітчизняних та іноземних програм",
                        max_length=1500,
                        verbose_name="Врахування досвіду аналогічних вітчизняних та іноземних програм",
                    ),
                ),
                (
                    "learning_experience_achieve",
                    models.TextField(
                        help_text="Продемонструйте, яким чином ОП дозволяє досягти результатів навчання, визначених стандартом вищої освіти за відповідною спеціальністю та рівнем вищої освіти (за наявності)",
                        max_length=3000,
                        verbose_name="Як ОП дозволяє досягти результатів навчання",
                    ),
                ),
                (
                    "national_qualifications_level",
                    models.TextField(
                        help_text="Якщо стандарт вищої освіти за відповідною спеціальністю та рівнем вищої освіти відсутній, поясніть, яким чином визначені ОП програмні результати навчання відповідають вимогам Національної рамки кваліфікацій для відповідного кваліфікаційного рівня? ",
                        max_length=3000,
                        verbose_name="Відповідність результатів ОП до рамки кваліфікацій при відсутності стандарту вищої освіти",
                    ),
                ),
            ],
            options={
                "verbose_name": "Проектування та цілі освітньої програми",
                "verbose_name_plural": "Проектування та цілі освітніх програми",
                "db_table": "education_program_design",
            },
        ),
        migrations.CreateModel(
            name="EducationalProgramDevelopmentPerspectives",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "strong_weak_points",
                    models.TextField(
                        help_text="Опис загальних сильних та слабких сторін ОП",
                        max_length=3000,
                        verbose_name="Сильні та слабкі сторони ОП",
                    ),
                ),
                (
                    "future_development",
                    models.TextField(
                        help_text="Опис конкретних заходів, які ЗВО планує здійснити для реалізації перспектив розвитку ОП",
                        max_length=1500,
                        verbose_name="Перспективи розвитку ОП на найближчі 3 роки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Перспектива подальшого розвитку ОП",
                "verbose_name_plural": "Перспективи подальшого розвитку ОП",
                "db_table": "op_development_perspectives",
            },
        ),
        migrations.CreateModel(
            name="EducationalProgramLearningAndTeaching",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "learning_and_teaching_methods",
                    models.TextField(
                        help_text="Продемонструйте, яким чином форми та методи навчання і викладання на ОП сприяють досягненню програмних результатів навчання? Наведіть посилання на відповідні документи",
                        max_length=1500,
                        verbose_name="Документи, що сприяють досягненню програмних результатів навчання",
                    ),
                ),
                (
                    "student_centered_approach",
                    models.TextField(
                        help_text="Продемонструйте, яким чином форми і методи навчання і викладання відповідають вимогам студентоцентрованого підходу? Яким є рівень задоволеності здобувачів вищої освіти методами навчання і викладання відповідно до результатів опитувань?",
                        max_length=1500,
                        verbose_name="Вимоги студентоцентрованого підходу",
                    ),
                ),
                (
                    "academic_freedom",
                    models.TextField(
                        help_text="Продемонструйте, яким чином забезпечується відповідність методів навчання і викладання на ОП принципам академічної свободи",
                        max_length=1500,
                        verbose_name="Відповідність методів за принципам академічної свободи",
                    ),
                ),
                (
                    "learning_outcomes",
                    models.TextField(
                        help_text="Опишіть, яким чином і у які строки учасникам освітнього процесу надається інформація щодо цілей, змісту та очікуваних результатів навчання, порядку та критеріїв оцінювання у межах окремих освітніх компонентів",
                        max_length=1500,
                        verbose_name="Строки надання інформації учасникам",
                    ),
                ),
                (
                    "learning_and_research",
                    models.TextField(
                        help_text="Опишіть, яким чином відбувається поєднання навчання і досліджень під час реалізації ОП",
                        max_length=3000,
                        verbose_name="Навчання та дослідження",
                    ),
                ),
                (
                    "curriculum_update",
                    models.TextField(
                        help_text="Продемонструйте, із посиланням на конкретні приклади, яким чином викладачі оновлюють зміст освітніх компонентів на основі наукових досягнень і сучасних практик у відповідній галузі",
                        max_length=3000,
                        verbose_name="Оновлення змісту навчальної програми",
                    ),
                ),
                (
                    "internationalization",
                    models.TextField(
                        help_text="Опишіть, яким чином навчання, викладання та наукові дослідження у межах ОП пов’язані із інтернаціоналізацією діяльності ЗВО",
                        max_length=1500,
                        verbose_name="Інтернаціоналізація діяльності",
                    ),
                ),
            ],
            options={
                "verbose_name": "Навчання і викладання за освітньою програмою",
                "verbose_name_plural": "Навчання і викладання за освітніх програм",
                "db_table": "educational_program_learning_and_teaching",
            },
        ),
        migrations.CreateModel(
            name="EducationalProgramStructureAndContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ep_credits_amount",
                    models.PositiveIntegerField(
                        help_text="Яким є обсяг ОП (у кредитах ЄКТС)?",
                        verbose_name="Обсяг ОП (у кредитах ЄКТС)",
                    ),
                ),
                (
                    "components_credits_amount",
                    models.PositiveSmallIntegerField(
                        help_text="Яким є обсяг освітніх компонентів (у кредитах ЄКТС), спрямованих на формування компетентностей, визначених стандартом вищої освіти за відповідною спеціальністю та рівнем вищої освіти (за наявності)?",
                        verbose_name="Обсяг кредитів для формування компетентностей",
                    ),
                ),
                (
                    "student_electives_credits_amount",
                    models.PositiveSmallIntegerField(
                        help_text="Який обсяг (у кредитах ЄКТС) відводиться на дисципліни за вибором здобувачів вищої освіти?",
                        verbose_name="Обсяг кредитів відведених на дисципліни",
                    ),
                ),
                (
                    "content_compliance",
                    models.TextField(
                        help_text="Продемонструйте, що зміст ОП відповідає предметній області заявленої для неї спеціальності (спеціальностям, якщо освітня програма є міждисциплінарною)",
                        max_length=3000,
                        verbose_name="Відповідність предметній області спеціальності",
                    ),
                ),
                (
                    "individual_learning_path",
                    models.TextField(
                        help_text="Яким чином здобувачам вищої освіти забезпечена можливість формування індивідуальної освітньої траєкторії?",
                        max_length=1500,
                        verbose_name="Забезпечення індивідуальної освітньої траєкторії",
                    ),
                ),
                (
                    "student_choice_right",
                    models.TextField(
                        help_text="Яким чином здобувачі вищої освіти можуть реалізувати своє право на вибір навчальних дисциплін?",
                        max_length=3000,
                        verbose_name="Право здобувачів на вибір навчальних дисциплін",
                    ),
                ),
                (
                    "student_practical_training",
                    models.TextField(
                        help_text="Опишіть, яким чином ОП та навчальний план передбачають практичну підготовку здобувачів вищої освіти, яка дозволяє здобути компетентності, необхідні для подальшої професійної діяльності",
                        max_length=1500,
                        verbose_name="Практична підготовка здобувачів",
                    ),
                ),
                (
                    "student_soft_skills",
                    models.TextField(
                        help_text="Продемонструйте, що ОП дозволяє забезпечити набуття здобувачами вищої освіти соціальних навичок (soft skills) упродовж періоду навчання, які відповідають цілям та результатам навчання ОП",
                        max_length=1500,
                        verbose_name="Соціальні навички здобувачів",
                    ),
                ),
                (
                    "relevant_professional_standard",
                    models.TextField(
                        help_text="Яким чином зміст ОП ураховує вимоги відповідного професійного стандарту?",
                        max_length=1500,
                        verbose_name="Вимоги професійного стандарту",
                    ),
                ),
                (
                    "components_scope_correlating_approach",
                    models.TextField(
                        help_text="Який підхід використовує ЗВО для співвіднесення обсягу окремих освітніх компонентів ОП (у кредитах ЄКТС) із фактичним навантаженням здобувачів вищої освіти (включно із самостійною роботою)?",
                        max_length=1500,
                        verbose_name="Підхід для співвіднесення обсягу компонентів ОП",
                    ),
                ),
                (
                    "dual_form_education_structure",
                    models.TextField(
                        help_text="Якщо за ОП здійснюється підготовка здобувачів вищої освіти за дуальною формою освіти, продемонструйте, яким чином структура освітньої програми та навчальний план зумовлюються завданнями та особливостями цієї форми здобуття освіти",
                        max_length=1500,
                        verbose_name="Структура ОП за дуальною формою освіти",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EducationalTransparencyAndPublicity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "regulatory_documents",
                    models.CharField(
                        help_text="Документи, що регулюють права та обов'язки усіх учасників освітнього процесу та їх доступність для учасників освітнього процесу.",
                        max_length=1500,
                        verbose_name="Регуляторні документи",
                    ),
                ),
                (
                    "stakeholder_feedback_link",
                    models.URLField(
                        help_text="Адреса веб-сторінки на офіційному веб-сайті ЗВО, де можна знайти проект з метою отримання зауважень та пропозицій від заінтересованих сторін (стейкхолдерів).",
                        verbose_name="Посилання на веб-сторінку для отримання зауважень та пропозицій",
                    ),
                ),
                (
                    "educational_program_link",
                    models.URLField(
                        help_text="Адреса веб-сторінки, де можна знайти оприлюднену у відкритому доступі в мережі Інтернет інформацію про освітню програму (включаючи її цілі, очікувані результати навчання та компоненти).",
                        verbose_name="Посилання на інформацію про освітню програму",
                    ),
                ),
            ],
            options={
                "verbose_name": "Прозорість та публічність",
                "verbose_name_plural": "Прозорість та публічність",
                "db_table": "educational_transparency_and_publicity",
            },
        ),
        migrations.CreateModel(
            name="HumanResources",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "competency_level",
                    models.TextField(
                        help_text="Яким чином під час конкурсного добору викладачів ОП забезпечується необхідний рівень їх професіоналізму?",
                        max_length=1500,
                        verbose_name="Рівень професіоналізму",
                    ),
                ),
                (
                    "employers_engagement",
                    models.TextField(
                        help_text="Опишіть, із посиланням на конкретні приклади, яким чином ЗВО залучає роботодавців до організації та реалізації освітнього процесу",
                        max_length=1500,
                        verbose_name="Залучення роботодавців",
                    ),
                ),
                (
                    "expert_involvement",
                    models.TextField(
                        help_text="Опишіть, із посиланням на конкретні приклади, яким чином ЗВО залучає до аудиторних занять на ОП професіоналів-практиків, експертів галузі, представників роботодавців",
                        max_length=1500,
                        verbose_name="Залучення професіоналів-практиків",
                    ),
                ),
                (
                    "teacher_development",
                    models.TextField(
                        help_text="Опишіть, яким чином ЗВО сприяє професійному розвиткові викладачів ОП? Наведіть конкретні приклади такого сприяння",
                        max_length=1500,
                        verbose_name="Розвиток викладачів ОП",
                    ),
                ),
                (
                    "teaching_excellence",
                    models.TextField(
                        help_text="Продемонструйте, що ЗВО стимулює розвиток викладацької майстерності",
                        max_length=1500,
                        verbose_name="Стимулювання розвитку викладацької майстерності",
                    ),
                ),
            ],
            options={
                "verbose_name": "Людський ресурс",
                "verbose_name_plural": "Людські ресурси",
                "db_table": "human_resources",
            },
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Назва мови", max_length=50, verbose_name="Мова"
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        help_text="Скорочення від повної назви",
                        max_length=250,
                        verbose_name="Код мови",
                    ),
                ),
            ],
            options={
                "verbose_name": "Мова",
                "verbose_name_plural": "Мови",
                "db_table": "language",
            },
        ),
        migrations.CreateModel(
            name="QualityAssurance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "regulatory_document",
                    models.TextField(
                        help_text="Яким документом ЗВО регулюються процедури розроблення, затвердження, моніторингу та періодичного перегляду ОП? Наведіть посилання на цей документ, оприлюднений у відкритому доступі в мережі Інтернет. ",
                        max_length=1500,
                        verbose_name="Регуляторний документ ОП",
                    ),
                ),
                (
                    "education_program_review",
                    models.TextField(
                        help_text="Опишіть, яким чином та з якою періодичністю відбувається перегляд ОП? Які зміни були внесені до ОП за результатами останнього перегляду, чим вони були обґрунтовані?",
                        max_length=3000,
                        verbose_name="Перегляд ОП",
                    ),
                ),
                (
                    "involvement_of_students",
                    models.TextField(
                        help_text="Продемонструйте, із посиланням на конкретні приклади, як здобувачі вищої освіти залучені до процесу періодичного перегляду ОП та інших процедур забезпечення її якості, а їх позиція береться до уваги під час перегляду ОП",
                        max_length=1500,
                        verbose_name="Залучення студентів до процесу періодичного перегляду ОП",
                    ),
                ),
                (
                    "student_self_government",
                    models.TextField(
                        help_text="Яким чином студентське самоврядування бере участь у процедурах внутрішнього забезпечення якості ОП",
                        max_length=1500,
                        verbose_name="Студентське самоврядування",
                    ),
                ),
                (
                    "involvement_of_employers",
                    models.TextField(
                        help_text="Продемонструйте, із посиланням на конкретні приклади, як роботодавці безпосередньо або через свої об’єднання залучені до процесу періодичного перегляду ОП та інших процедур забезпечення її якості.",
                        max_length=1500,
                        verbose_name="Залучення роботодавців",
                    ),
                ),
                (
                    "alumni_employment",
                    models.TextField(
                        help_text="Опишіть практику збирання та врахування інформації щодо кар’єрного шляху та траєкторій працевлаштування випускників ОП.",
                        max_length=1500,
                        verbose_name="Траєкторії працевлаштування випускників ОП",
                    ),
                ),
                (
                    "quality_issues",
                    models.TextField(
                        help_text="Які недоліки в ОП та/або освітній діяльності з реалізації ОП були виявлені у ході здійснення процедур внутрішнього забезпечення якості за час її реалізації? Яким чином система забезпечення якості ЗВО відреагувала на ці недоліки?.",
                        max_length=3000,
                        verbose_name="Недоліки в ОП та реакція на них",
                    ),
                ),
                (
                    "educational_program_improvement",
                    models.TextField(
                        help_text="Продемонструйте, що результати зовнішнього забезпечення якості вищої освіти беруться до уваги під час удосконалення ОП. Яким чином зауваження та пропозиції з останньої акредитації та акредитацій інших ОП були ураховані під час удосконалення цієї ОП?.",
                        max_length=3000,
                        verbose_name="Удосконалення ОП",
                    ),
                ),
                (
                    "academic_community_members_engaging",
                    models.TextField(
                        help_text="Опишіть, яким чином учасники академічної спільноти змістовно залучені до процедур внутрішнього забезпечення якості ОП?.",
                        max_length=1500,
                        verbose_name="Залучення учасників академічної спільноти",
                    ),
                ),
                (
                    "structural_units_responsibilities_distribution",
                    models.TextField(
                        help_text="Опишіть розподіл відповідальності між різними структурними підрозділами ЗВО у контексті здійснення процесів і процедур внутрішнього забезпечення якості освіти.",
                        max_length=1500,
                        verbose_name="Розподіл відповідальності між різними структурними підрозділами ЗВО",
                    ),
                ),
            ],
            options={
                "verbose_name": "Внутрішнє забезпечення якості освітньої програми",
                "verbose_name_plural": "Внутрішнє забезпечення якості освітніх програм",
                "db_table": "quality_assurance",
            },
        ),
        migrations.CreateModel(
            name="GeneralQuestionAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "control_measures_and_academic_integrity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="general_question_answer.controlmeasuresandacademicintegrity",
                        verbose_name="Контрольні заходи, оцінювання здобувачів вищої освіти та академічна доброчесність",
                    ),
                ),
                (
                    "educational_environment_and_material_resources",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="general_question_answer.educationalenvironmentandmaterialresources",
                        verbose_name="Освітнє середовище та матеріальні ресурси",
                    ),
                ),
                (
                    "educational_program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="general_question_answer.educationalprogram",
                        verbose_name="EducationalProgram",
                    ),
                ),
                (
                    "educational_program_access",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="general_question_answer.educationalprogramaccess",
                        verbose_name="Доступ до освітньої програми та визнання результатів навчання",
                    ),
                ),
                (
                    "educational_program_design",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="general_question_answer.educationalprogramdesign",
                        verbose_name="Проектування та цілі освітньої програми",
                    ),
                ),
                (
                    "educational_program_development_perspectives",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="general_question_answer.educationalprogramdevelopmentperspectives",
                        verbose_name="Перспективи подальшого розвитку ОП",
                    ),
                ),
                (
                    "educational_program_learning_and_teaching",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="general_question_answer.educationalprogramlearningandteaching",
                        verbose_name="Навчання і викладання за освітньою програмою",
                    ),
                ),
                (
                    "educational_program_structure_and_content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="general_question_answer.educationalprogramstructureandcontent",
                        verbose_name="Структура та зміст освітньої програми",
                    ),
                ),
                (
                    "educational_transparency_and_publicity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="general_question_answer.educationaltransparencyandpublicity",
                        verbose_name="Прозорість і публічність",
                    ),
                ),
                (
                    "human_resources",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="general_question_answer.humanresources",
                        verbose_name="Людські ресурси",
                    ),
                ),
                (
                    "quality_assurance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="general_question_answer.qualityassurance",
                        verbose_name="Внутрішнє забезпечення якості освітньої програми",
                    ),
                ),
            ],
            options={
                "verbose_name": "Додаток до довідника про самооцінювання ОП(таблиці)",
                "verbose_name_plural": "Додатки до довідника про самооцінювання ОП(таблиці)",
                "db_table": "general_question_answer",
            },
        ),
    ]
