# Generated by Django 4.0.10 on 2024-10-10 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("general_question_answer", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="educationalprogram",
            options={
                "verbose_name": "Навчання через дослідження",
                "verbose_name_plural": "Навчання через дослідження",
            },
        ),
    ]
