# Generated by Django 4.0.10 on 2024-10-10 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general_information", "0004_alter_educationstatistics_study_course_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="educationstatistics",
            name="study_course_year",
            field=models.IntegerField(
                choices=[
                    (1, "1 рік навчання"),
                    (2, "2 рік навчання"),
                    (3, "3 рік навчання"),
                    (4, "4 рік навчання"),
                ],
                help_text="Рік навчання",
                verbose_name="Рік навчання",
            ),
        ),
    ]
