# Generated by Django 4.0.10 on 2023-05-04 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_teacher_student'),
        ('general_information', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalProgramComponentsInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_name', models.CharField(help_text="Назва обов'язкового освітнього компонента", max_length=255, verbose_name='Назва освітнього компонента')),
                ('component_type', models.CharField(help_text="Вид обов'язкового освітнього компонента", max_length=255, verbose_name='Вид компонента')),
                ('syllabus', models.FileField(blank=True, help_text='Поле для завантаження силабуса або інших навчально-методичних матеріалів', max_length=255, null=True, upload_to='syllabus/', verbose_name='Поле завантаження силабуса/навчально-методичних матеріалів')),
                ('special_equipment_info', models.TextField(help_text='Якщо освітній компонент потребує спеціального матеріально-технічного та/або інформаційного забезпечення, наведіть відомості щодо нього*', verbose_name='Інформація про спеціальне обладнання')),
            ],
            options={
                'verbose_name': 'Інформація про обов’язковий освітній компонент ОП',
                'verbose_name_plural': 'Інформація про обов’язкові освітні компоненти ОП',
                'db_table': 'program_educational_components_information',
            },
        ),
        migrations.CreateModel(
            name='ProgramLearningOutcomeCorrespondenceMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Назва програмного результату навчання', max_length=3000, verbose_name='Результати навчання')),
                ('teaching_method', models.CharField(help_text='Назва методу навчання', max_length=1000, verbose_name='Методи навчання')),
                ('assessment_form', models.CharField(help_text='Назва форми оцінювання', max_length=200, verbose_name='Форми оцінювання')),
                ('educational_component', models.ForeignKey(help_text='Назва освітнього компонента', on_delete=django.db.models.deletion.CASCADE, to='table_annex.educationalprogramcomponentsinformation', verbose_name='Освітній компонент')),
            ],
            options={
                'verbose_name': 'Матриця відповідності програмних результатів навчання, освітніх компонентів, методів навчання та оцінювання',
                'verbose_name_plural': 'Матриця відповідності програмних результатів навчання, освітніх компонентів, методів навчання та оцінювання',
                'db_table': 'program_learning_outcome_correspondence_matrix',
            },
        ),
        migrations.CreateModel(
            name='TeacherSummaryInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_qualification', models.CharField(help_text='Інформація про кваліфікацію викладача', max_length=200, verbose_name='Кваліфікація викладача')),
                ('teacher_experience', models.IntegerField(help_text='Стаж науково-педагогічної роботи в роках', verbose_name='Стаж роботи')),
                ('education_disciplines', models.TextField(help_text='Навчальні дисципліни, що їх викладає викладач на ОП', verbose_name='Навчальні дисципліни')),
                ('rationale', models.TextField(help_text='Обґрунтування', verbose_name='Обґрунтування')),
                ('structural_subdivision', models.ForeignKey(help_text='Структурний підрозділ, у якому працює викладач', on_delete=django.db.models.deletion.PROTECT, related_name='structural_subdivision_teacher_information', to='general_information.structuralsubdivision')),
                ('teacher_full_name', models.ForeignKey(help_text="Повне ім'я викладача", on_delete=django.db.models.deletion.PROTECT, to='users.teacher', verbose_name='ПІБ викладача')),
            ],
            options={
                'verbose_name': 'Зведена інформація про викладача',
                'verbose_name_plural': 'Зведена інформація про викладачів',
                'db_table': 'teacher_summary_information',
            },
        ),
        migrations.CreateModel(
            name='TablesAnnex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_educational_components_information', models.ForeignKey(help_text='Наводять відомості, як мінімум, щодо наявності відповідного матеріально-технічного забезпечення, його достатності для реалізації ОП; для обладнання/устаткування – також кількість, рік введення в експлуатацію, рік останнього ремонту; для програмного забезпечення – також кількість ліцензій та версія програмного забезпечення', on_delete=django.db.models.deletion.PROTECT, related_name='components_information_tables_annex', to='table_annex.educationalprogramcomponentsinformation', verbose_name='Інформація про обов’язкові освітні компоненти ОП')),
                ('program_learning_outcome_correspondence_matrix', models.ManyToManyField(help_text='Для кожного освітнього компонента заповнюється окрема таблиця.', related_name='correspondence_matrix_tables_annex', to='table_annex.programlearningoutcomecorrespondencematrix', verbose_name='Матриця відповідності програмних результатів навчання, освітніх компонентів, методів навчання та оцінювання')),
                ('teacher_summary_information', models.ForeignKey(help_text='Обґрунтування зазначається окремо щодо кожної дисципліни, яку викладає викладач.', on_delete=django.db.models.deletion.PROTECT, related_name='teacher_summary_information_tables_annex', to='table_annex.teachersummaryinformation', verbose_name='Зведена інформація про викладачів')),
            ],
            options={
                'verbose_name': 'Відповідь на загальні питання',
                'verbose_name_plural': 'Відповіді на загальні питання',
                'db_table': 'table_annex',
            },
        ),
    ]
